### ISSUE TITLE
Completely remove node_modules/prisma folder

### ISSUE THREAD

**Issue by HenriJ** [danieluhm2004/serverless-webpack-prisma#4]
In the packaged lambda, I see the engine .so files in multiple locations:

- node_modules/prisma/engines/34df67547cf5598f5a6cd3eb45f14ee70c3fb86f/libquery_engine-rhel-openssl-1.0.x.so.node
- node_modules/.prisma/client/libquery_engine-rhel-openssl-1.0.x.so.node

I understand that we have the engine in `.prisma`, but I guess we don't need the one on `prisma`, and even more, do we need the `prisma` folder at all ?

**Comment by HenriJ** [comment]
I added to my serverless.ts file this in addition to using your plugin:
```
    scriptable: {
      hooks: {
        "after:webpack:package:packExternalModules":
          "rm -R .webpack/service/node_modules/.bin/** && rm -R .webpack/service/node_modules/prisma/**",
      },
    },
```

It seems to be working like that

**Comment by danieluhm2004** [comment]
Hello @HenriJ 

When I was developing and debugging, I realized that the contents of the ``.prisma`` and ``@prisma/client`` libraries should not be deleted.

A pattern that can be erased is provided [here](https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-aws-lambda#package-pattern-in-serverlessyml)

Since ``serverless-webpack-prisma`` already **removes unnecessary files**, there is no need to take any **action such as deleting additional files**.

_If you delete more than that, it will not work smoothly._

thank you.

**Comment by danieluhm2004** [comment]
I will close the issue. If you have any related issues, please open it again. :)
